Media Queries: Squash invalid use of unused variable warning.
error: ‘last’ may be used uninitialized in this function [-Werror=maybe-uninitialized]